SENTRY_AUTH_TOKEN ?= OVERRIDE
SENTRY_ORG ?= OVERRIDE
SENTRY_PROJECT ?= OVERRIDE

docker_build:
	docker build --build-arg SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN} --build-arg SENTRY_ORG=${SENTRY_ORG} --build-arg SENTRY_PROJECT=${SENTRY_PROJECT} -t test .
